course_mapping = {
    "ME5128": "Thermal Management in Electric Vehicles",
    "ME5120": "Advanced Machining Processes",
    "ME5125": "Mechanical Design Simulation",
    "ME5103": "Design of Heat Exchangers",
    "ME5127": "Multiscale Modeling of Materials Using Machine Learning",
    "ME5123": "Laser-Based Manufacturing Techniques",
    "CS6100": "Computer Vision",
    "CS6103": "Computer and Network Security",
    "CS5108": "Algorithmic Graph Theory",
    "CS3007": "Pattern Recognition and Machine Learning",
    "CS5001": "Advanced Data Structures and Algorithms",
    "CS5105": "Machine Learning",
    "EC5101": "Introduction to Photonics",
    "ID6100": "Energy Harvesting Technology",
    "BM5102": "Medical Imaging Systems",
    "EC4100": "RF and Microwave Circuit Design",
    "MA1000": "Calculus",
    "PH1000": "Engineering Electromagnetics",
    "EC1000": "Electrical Circuits for Engineers",
    "CS1000": "Problem Solving and Programming",
    "ME1000": "Materials for Engineers",
    "DS1000": "Foundation for Engineering and Product Design",
    "MA1001": "Differential Equations",
    "ME1001": "Engineering Graphics",
    "CS1002": "Elementary Data Structures and Logical Thinking",
    "MA1002": "Linear Algebra",
    "CS1005": "Discrete Structures for Computer Science",
    "CS2005": "Applied Data Science",
    "CS2000": "Object-Oriented Programming",
    "CS2001": "Digital System Design",
    "CS2002": "Design and Analysis of Algorithms",
    "CS2012": "Artificial Intelligence",
    "MA2000": "Optimization Techniques for Machine Learning",
    "CS2007": "Computer Organization and Architecture",
    "CS2008": "Database Systems",
    "CS2009": "Theory of Computation",
    "DS1001": "Sociology of Design",
    "DS2000": "Systems Thinking for Design",
    "DS2001": "Smart Product Design",
    "EC1001": "Digital Circuits",
    "EC2000": "Solid State Electronic Devices",
    "EC2001": "Network Theory",
    "EC2002": "Signals and Systems",
    "EC2003": "Microprocessors and Microcontrollers",
    "EC2007": "Digital Signal Processing",
    "EC2008": "Electromagnetic Waves",
    "EC2009": "Analog Circuits",
    "ME2000": "Engineering Thermodynamics",
    "ME2001": "Fluid Mechanics and Fluid Machinery",
    "ME2002": "Mechanics of Materials",
    "ME2003": "Manufacturing Processes - 1",
    "ME2005": "Heat Transfer",
    "ME2006": "Kinematics and Dynamics of Machinery",
    "ME3000": "Design of Machine Elements",
    "ME3001": "Measurement and Automation"
}
